name: Build Image & Deploy to Azure

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         submodules: true
         lfs: false
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          [string]$projFile = Get-Content ./src/telefone-book-api/telefone-book-api.csproj
          $xDoc = [System.Xml.Linq.XDocument]::Parse($projFile)
          $version = $xDoc.Element("Project")?.Element("PropertyGroup")?.Element("AssemblyVersion")?.Value ?? "0.0.1"
          echo "ImageVersion=$version" >> $env:GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zaoneg/telephone-book-api:${{ env.ImageVersion }}
